<?php

/**
*   Takealot Assesment
*
*   A simple IP Address Validator application.
*
*   You should be able to add, update and remove a contact.
*   An alert message will be displayed indication the results
*   of the action.
*
*   @author Albert Nel
*/

ini_set("auto_detect_line_endings", true);

/*
*   Include the autoload.php file as generated by composer
*   to load all dependencies.
*/
require __DIR__ . '/../vendor/autoload.php';

/**
*   Include other application classes and files.
*/
require_once __DIR__ . '/utils.php';
require_once __DIR__ . '/AppController.php';

/**
*   Initialize Twig templating engine.
*/
function loadTwig()
{
    // Initialize twig
    Twig_Autoloader::register();
    $loader = new Twig_Loader_Filesystem(__DIR__ . '/templates');
    $twig = new Twig_Environment($loader, array());

    return $twig;
}

/**
* Route handlers.
*/
function indexHandler()
{
    $app = new AppController();
    $app->displayIndexPage();
}

function aboutHandler()
{
    $twig = loadTwig();
    echo $twig->render('about.html');
}

/**
*   Configure routes for the app.
*/
$dispatcher = \FastRoute\simpleDispatcher(function (\FastRoute\RouteCollector $r) {
    // Add routes
    $r->addRoute(['GET', 'POST'], '/', 'indexHandler');
    $r->addRoute('GET', '/about', 'aboutHandler');
});

/**
*   Get the HTTP method and URI.
*/
$httpMethod = $_SERVER['REQUEST_METHOD'];
$uri = $_SERVER['REQUEST_URI'];

/**
*   Strip query string and decode URI.
*/
if (false !== $pos = strpos($uri, '?')) {
    $uri = substr($uri, 0, $pos);
}
$uri = rawurldecode($uri);

/**
*   Dispatch route.
*/
$routeInfo = $dispatcher->dispatch($httpMethod, $uri);
switch ($routeInfo[0]) {
    case \FastRoute\Dispatcher::NOT_FOUND:
        // ... 404 Not Found
        break;
    case \FastRoute\Dispatcher::METHOD_NOT_ALLOWED:
        $allowedMethods = $routeInfo[1];
        // ... 405 Method Not Allowed
        break;
    case \FastRoute\Dispatcher::FOUND:
        $handler = $routeInfo[1];
        $vars = $routeInfo[2];
        call_user_func($handler, $vars);
        break;
}

?>
